-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.10.2.115
-- Module  Version: 6.5
--C:\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n mem_9_1024 -lang vhdl -synth synplify -bus_exp 7 -bb -arch xo3c00f -type bram -wp 10 -rp 0011 -rdata_width 9 -data_width 9 -num_rows 1024 -cascade -1 -mem_init0

-- Mon Jun 25 07:13:56 2018

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO3L;
use MACHXO3L.components.all;
-- synopsys translate_on

entity mem_9_1024 is
    port (
        WrAddress: in  std_logic_vector(9 downto 0);
        RdAddress: in  std_logic_vector(9 downto 0);
        Data: in  std_logic_vector(8 downto 0);
        WE: in  std_logic;
        RdClock: in  std_logic;
        RdClockEn: in  std_logic;
        Reset: in  std_logic;
        WrClock: in  std_logic;
        WrClockEn: in  std_logic;
        Q: out  std_logic_vector(8 downto 0));
end mem_9_1024;

architecture Structure of mem_9_1024 is

    -- internal signal declarations
    signal scuba_vhi: std_logic;
    signal scuba_vlo: std_logic;

    -- local component declarations
    component VHI
        port (Z: out  std_logic);
    end component;
    component VLO
        port (Z: out  std_logic);
    end component;
    component DP8KC
        generic (INIT_DATA : in String; INITVAL_1F : in String;
                INITVAL_1E : in String; INITVAL_1D : in String;
                INITVAL_1C : in String; INITVAL_1B : in String;
                INITVAL_1A : in String; INITVAL_19 : in String;
                INITVAL_18 : in String; INITVAL_17 : in String;
                INITVAL_16 : in String; INITVAL_15 : in String;
                INITVAL_14 : in String; INITVAL_13 : in String;
                INITVAL_12 : in String; INITVAL_11 : in String;
                INITVAL_10 : in String; INITVAL_0F : in String;
                INITVAL_0E : in String; INITVAL_0D : in String;
                INITVAL_0C : in String; INITVAL_0B : in String;
                INITVAL_0A : in String; INITVAL_09 : in String;
                INITVAL_08 : in String; INITVAL_07 : in String;
                INITVAL_06 : in String; INITVAL_05 : in String;
                INITVAL_04 : in String; INITVAL_03 : in String;
                INITVAL_02 : in String; INITVAL_01 : in String;
                INITVAL_00 : in String; ASYNC_RESET_RELEASE : in String;
                RESETMODE : in String; GSR : in String;
                WRITEMODE_B : in String; WRITEMODE_A : in String;
                CSDECODE_B : in String; CSDECODE_A : in String;
                REGMODE_B : in String; REGMODE_A : in String;
                DATA_WIDTH_B : in Integer; DATA_WIDTH_A : in Integer);
        port (DIA8: in  std_logic; DIA7: in  std_logic;
            DIA6: in  std_logic; DIA5: in  std_logic;
            DIA4: in  std_logic; DIA3: in  std_logic;
            DIA2: in  std_logic; DIA1: in  std_logic;
            DIA0: in  std_logic; ADA12: in  std_logic;
            ADA11: in  std_logic; ADA10: in  std_logic;
            ADA9: in  std_logic; ADA8: in  std_logic;
            ADA7: in  std_logic; ADA6: in  std_logic;
            ADA5: in  std_logic; ADA4: in  std_logic;
            ADA3: in  std_logic; ADA2: in  std_logic;
            ADA1: in  std_logic; ADA0: in  std_logic; CEA: in  std_logic;
            OCEA: in  std_logic; CLKA: in  std_logic; WEA: in  std_logic;
            CSA2: in  std_logic; CSA1: in  std_logic;
            CSA0: in  std_logic; RSTA: in  std_logic;
            DIB8: in  std_logic; DIB7: in  std_logic;
            DIB6: in  std_logic; DIB5: in  std_logic;
            DIB4: in  std_logic; DIB3: in  std_logic;
            DIB2: in  std_logic; DIB1: in  std_logic;
            DIB0: in  std_logic; ADB12: in  std_logic;
            ADB11: in  std_logic; ADB10: in  std_logic;
            ADB9: in  std_logic; ADB8: in  std_logic;
            ADB7: in  std_logic; ADB6: in  std_logic;
            ADB5: in  std_logic; ADB4: in  std_logic;
            ADB3: in  std_logic; ADB2: in  std_logic;
            ADB1: in  std_logic; ADB0: in  std_logic; CEB: in  std_logic;
            OCEB: in  std_logic; CLKB: in  std_logic; WEB: in  std_logic;
            CSB2: in  std_logic; CSB1: in  std_logic;
            CSB0: in  std_logic; RSTB: in  std_logic;
            DOA8: out  std_logic; DOA7: out  std_logic;
            DOA6: out  std_logic; DOA5: out  std_logic;
            DOA4: out  std_logic; DOA3: out  std_logic;
            DOA2: out  std_logic; DOA1: out  std_logic;
            DOA0: out  std_logic; DOB8: out  std_logic;
            DOB7: out  std_logic; DOB6: out  std_logic;
            DOB5: out  std_logic; DOB4: out  std_logic;
            DOB3: out  std_logic; DOB2: out  std_logic;
            DOB1: out  std_logic; DOB0: out  std_logic);
    end component;
    attribute MEM_LPC_FILE : string;
    attribute MEM_INIT_FILE : string;
    attribute MEM_LPC_FILE of mem_9_1024_0_0_0 : label is "mem_9_1024.lpc";
    attribute MEM_INIT_FILE of mem_9_1024_0_0_0 : label is "INIT_ALL_0s";
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    mem_9_1024_0_0_0: DP8KC
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC",
        INITVAL_1F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_1E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_1D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_1C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_1B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_1A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_19=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_18=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_17=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_16=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_15=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_14=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_13=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_12=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_11=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_10=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_0F=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_0E=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_0D=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_0C=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_0B=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_0A=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_09=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_08=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_07=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_06=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_05=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_04=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_03=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_02=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_01=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        INITVAL_00=> "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        CSDECODE_B=> "0b000", CSDECODE_A=> "0b000", WRITEMODE_B=> "NORMAL",
        WRITEMODE_A=> "NORMAL", GSR=> "ENABLED", RESETMODE=> "ASYNC",
        REGMODE_B=> "NOREG", REGMODE_A=> "NOREG", DATA_WIDTH_B=>  9,
        DATA_WIDTH_A=>  9)
        port map (DIA8=>Data(8), DIA7=>Data(7), DIA6=>Data(6),
            DIA5=>Data(5), DIA4=>Data(4), DIA3=>Data(3), DIA2=>Data(2),
            DIA1=>Data(1), DIA0=>Data(0), ADA12=>WrAddress(9),
            ADA11=>WrAddress(8), ADA10=>WrAddress(7), ADA9=>WrAddress(6),
            ADA8=>WrAddress(5), ADA7=>WrAddress(4), ADA6=>WrAddress(3),
            ADA5=>WrAddress(2), ADA4=>WrAddress(1), ADA3=>WrAddress(0),
            ADA2=>scuba_vlo, ADA1=>scuba_vlo, ADA0=>scuba_vhi,
            CEA=>WrClockEn, OCEA=>WrClockEn, CLKA=>WrClock, WEA=>WE,
            CSA2=>scuba_vlo, CSA1=>scuba_vlo, CSA0=>scuba_vlo,
            RSTA=>Reset, DIB8=>scuba_vlo, DIB7=>scuba_vlo,
            DIB6=>scuba_vlo, DIB5=>scuba_vlo, DIB4=>scuba_vlo,
            DIB3=>scuba_vlo, DIB2=>scuba_vlo, DIB1=>scuba_vlo,
            DIB0=>scuba_vlo, ADB12=>RdAddress(9), ADB11=>RdAddress(8),
            ADB10=>RdAddress(7), ADB9=>RdAddress(6), ADB8=>RdAddress(5),
            ADB7=>RdAddress(4), ADB6=>RdAddress(3), ADB5=>RdAddress(2),
            ADB4=>RdAddress(1), ADB3=>RdAddress(0), ADB2=>scuba_vlo,
            ADB1=>scuba_vlo, ADB0=>scuba_vlo, CEB=>RdClockEn,
            OCEB=>RdClockEn, CLKB=>RdClock, WEB=>scuba_vlo,
            CSB2=>scuba_vlo, CSB1=>scuba_vlo, CSB0=>scuba_vlo,
            RSTB=>Reset, DOA8=>open, DOA7=>open, DOA6=>open, DOA5=>open,
            DOA4=>open, DOA3=>open, DOA2=>open, DOA1=>open, DOA0=>open,
            DOB8=>Q(8), DOB7=>Q(7), DOB6=>Q(6), DOB5=>Q(5), DOB4=>Q(4),
            DOB3=>Q(3), DOB2=>Q(2), DOB1=>Q(1), DOB0=>Q(0));

end Structure;

-- synopsys translate_off
library MACHXO3L;
configuration Structure_CON of mem_9_1024 is
    for Structure
        for all:VHI use entity MACHXO3L.VHI(V); end for;
        for all:VLO use entity MACHXO3L.VLO(V); end for;
        for all:DP8KC use entity MACHXO3L.DP8KC(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
