-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.11.2.446
-- Module  Version: 5.1
--C:\lscc\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe -w -n pci_read_request_fifo -lang vhdl -synth synplify -bus_exp 7 -bb -arch sa5p00g -type ebfifo -sync_mode -pfu_fifo -depth 8 -width 49 -regout -no_enable -pe -1 -pf -1 -reset_rel SYNC -fdc C:/Users/grpa/Documents/WORK/JADE/Systembus/BP_Test/ip_cores/pci_read_request_fifo/pci_read_request_fifo.fdc

-- Thu Feb 13 12:46:33 2020

library IEEE;
use IEEE.std_logic_1164.all;
library ecp5um;
use ecp5um.components.all;

entity pci_read_request_fifo is
    port (
        Data: in  std_logic_vector(48 downto 0);
        Clock: in  std_logic;
        WrEn: in  std_logic;
        RdEn: in  std_logic;
        Reset: in  std_logic;
        Q: out  std_logic_vector(48 downto 0);
        Empty: out  std_logic;
        Full: out  std_logic);
end pci_read_request_fifo;

architecture Structure of pci_read_request_fifo is

    -- internal signal declarations
    signal invout_1: std_logic;
    signal invout_0: std_logic;
    signal rden_i_inv: std_logic;
    signal fcnt_en: std_logic;
    signal empty_i: std_logic;
    signal empty_d: std_logic;
    signal full_i: std_logic;
    signal full_d: std_logic;
    signal edataout0: std_logic;
    signal edataout1: std_logic;
    signal edataout2: std_logic;
    signal edataout3: std_logic;
    signal edataout4: std_logic;
    signal edataout5: std_logic;
    signal edataout6: std_logic;
    signal edataout7: std_logic;
    signal edataout8: std_logic;
    signal edataout9: std_logic;
    signal edataout10: std_logic;
    signal edataout11: std_logic;
    signal edataout12: std_logic;
    signal edataout13: std_logic;
    signal edataout14: std_logic;
    signal edataout15: std_logic;
    signal edataout16: std_logic;
    signal edataout17: std_logic;
    signal edataout18: std_logic;
    signal edataout19: std_logic;
    signal edataout20: std_logic;
    signal edataout21: std_logic;
    signal edataout22: std_logic;
    signal edataout23: std_logic;
    signal edataout24: std_logic;
    signal edataout25: std_logic;
    signal edataout26: std_logic;
    signal edataout27: std_logic;
    signal edataout28: std_logic;
    signal edataout29: std_logic;
    signal edataout30: std_logic;
    signal edataout31: std_logic;
    signal edataout32: std_logic;
    signal edataout33: std_logic;
    signal edataout34: std_logic;
    signal edataout35: std_logic;
    signal edataout36: std_logic;
    signal edataout37: std_logic;
    signal edataout38: std_logic;
    signal edataout39: std_logic;
    signal edataout40: std_logic;
    signal edataout41: std_logic;
    signal edataout42: std_logic;
    signal edataout43: std_logic;
    signal edataout44: std_logic;
    signal edataout45: std_logic;
    signal edataout46: std_logic;
    signal edataout47: std_logic;
    signal edataout48: std_logic;
    signal ifcount_0: std_logic;
    signal ifcount_1: std_logic;
    signal bdcnt_bctr_ci: std_logic;
    signal ifcount_2: std_logic;
    signal ifcount_3: std_logic;
    signal co1: std_logic;
    signal cnt_con: std_logic;
    signal co0: std_logic;
    signal cmp_ci: std_logic;
    signal rden_i: std_logic;
    signal co0_1: std_logic;
    signal cmp_le_1: std_logic;
    signal cmp_le_1_c: std_logic;
    signal cmp_ci_1: std_logic;
    signal fcount_0: std_logic;
    signal fcount_1: std_logic;
    signal co0_2: std_logic;
    signal wren_i: std_logic;
    signal wren_i_inv: std_logic;
    signal fcount_2: std_logic;
    signal fcount_3: std_logic;
    signal cmp_ge_d1: std_logic;
    signal cmp_ge_d1_c: std_logic;
    signal iwcount_0: std_logic;
    signal iwcount_1: std_logic;
    signal w_ctr_ci: std_logic;
    signal iwcount_2: std_logic;
    signal iwcount_3: std_logic;
    signal co1_1: std_logic;
    signal co0_3: std_logic;
    signal wcount_3: std_logic;
    signal ircount_0: std_logic;
    signal ircount_1: std_logic;
    signal r_ctr_ci: std_logic;
    signal ircount_2: std_logic;
    signal ircount_3: std_logic;
    signal co1_2: std_logic;
    signal scuba_vlo: std_logic;
    signal co0_4: std_logic;
    signal rcount_3: std_logic;
    signal rdataout48: std_logic;
    signal rdataout47: std_logic;
    signal rdataout46: std_logic;
    signal rdataout45: std_logic;
    signal rdataout44: std_logic;
    signal rdataout43: std_logic;
    signal rdataout42: std_logic;
    signal rdataout41: std_logic;
    signal rdataout40: std_logic;
    signal rdataout39: std_logic;
    signal rdataout38: std_logic;
    signal rdataout37: std_logic;
    signal rdataout36: std_logic;
    signal rdataout35: std_logic;
    signal rdataout34: std_logic;
    signal rdataout33: std_logic;
    signal rdataout32: std_logic;
    signal rdataout31: std_logic;
    signal rdataout30: std_logic;
    signal rdataout29: std_logic;
    signal rdataout28: std_logic;
    signal rdataout27: std_logic;
    signal rdataout26: std_logic;
    signal rdataout25: std_logic;
    signal rdataout24: std_logic;
    signal rdataout23: std_logic;
    signal rdataout22: std_logic;
    signal rdataout21: std_logic;
    signal rdataout20: std_logic;
    signal rdataout19: std_logic;
    signal rdataout18: std_logic;
    signal rdataout17: std_logic;
    signal rdataout16: std_logic;
    signal rdataout15: std_logic;
    signal rdataout14: std_logic;
    signal rdataout13: std_logic;
    signal rdataout12: std_logic;
    signal rdataout11: std_logic;
    signal rdataout10: std_logic;
    signal rdataout9: std_logic;
    signal rdataout8: std_logic;
    signal rdataout7: std_logic;
    signal rdataout6: std_logic;
    signal rdataout5: std_logic;
    signal rdataout4: std_logic;
    signal rdataout3: std_logic;
    signal rdataout2: std_logic;
    signal rdataout1: std_logic;
    signal rdataout0: std_logic;
    signal rcount_2: std_logic;
    signal rcount_1: std_logic;
    signal rcount_0: std_logic;
    signal dec0_wre3: std_logic;
    signal scuba_vhi: std_logic;
    signal wcount_2: std_logic;
    signal wcount_1: std_logic;
    signal wcount_0: std_logic;

    attribute GSR : string;
    attribute MEM_INIT_FILE : string;
    attribute MEM_LPC_FILE : string;
    attribute COMP : string;
    attribute GSR of FF_111 : label is "ENABLED";
    attribute GSR of FF_110 : label is "ENABLED";
    attribute GSR of FF_109 : label is "ENABLED";
    attribute GSR of FF_108 : label is "ENABLED";
    attribute GSR of FF_107 : label is "ENABLED";
    attribute GSR of FF_106 : label is "ENABLED";
    attribute GSR of FF_105 : label is "ENABLED";
    attribute GSR of FF_104 : label is "ENABLED";
    attribute GSR of FF_103 : label is "ENABLED";
    attribute GSR of FF_102 : label is "ENABLED";
    attribute GSR of FF_101 : label is "ENABLED";
    attribute GSR of FF_100 : label is "ENABLED";
    attribute GSR of FF_99 : label is "ENABLED";
    attribute GSR of FF_98 : label is "ENABLED";
    attribute GSR of FF_97 : label is "ENABLED";
    attribute GSR of FF_96 : label is "ENABLED";
    attribute GSR of FF_95 : label is "ENABLED";
    attribute GSR of FF_94 : label is "ENABLED";
    attribute GSR of FF_93 : label is "ENABLED";
    attribute GSR of FF_92 : label is "ENABLED";
    attribute GSR of FF_91 : label is "ENABLED";
    attribute GSR of FF_90 : label is "ENABLED";
    attribute GSR of FF_89 : label is "ENABLED";
    attribute GSR of FF_88 : label is "ENABLED";
    attribute GSR of FF_87 : label is "ENABLED";
    attribute GSR of FF_86 : label is "ENABLED";
    attribute GSR of FF_85 : label is "ENABLED";
    attribute GSR of FF_84 : label is "ENABLED";
    attribute GSR of FF_83 : label is "ENABLED";
    attribute GSR of FF_82 : label is "ENABLED";
    attribute GSR of FF_81 : label is "ENABLED";
    attribute GSR of FF_80 : label is "ENABLED";
    attribute GSR of FF_79 : label is "ENABLED";
    attribute GSR of FF_78 : label is "ENABLED";
    attribute GSR of FF_77 : label is "ENABLED";
    attribute GSR of FF_76 : label is "ENABLED";
    attribute GSR of FF_75 : label is "ENABLED";
    attribute GSR of FF_74 : label is "ENABLED";
    attribute GSR of FF_73 : label is "ENABLED";
    attribute GSR of FF_72 : label is "ENABLED";
    attribute GSR of FF_71 : label is "ENABLED";
    attribute GSR of FF_70 : label is "ENABLED";
    attribute GSR of FF_69 : label is "ENABLED";
    attribute GSR of FF_68 : label is "ENABLED";
    attribute GSR of FF_67 : label is "ENABLED";
    attribute GSR of FF_66 : label is "ENABLED";
    attribute GSR of FF_65 : label is "ENABLED";
    attribute GSR of FF_64 : label is "ENABLED";
    attribute GSR of FF_63 : label is "ENABLED";
    attribute GSR of FF_62 : label is "ENABLED";
    attribute GSR of FF_61 : label is "ENABLED";
    attribute GSR of FF_60 : label is "ENABLED";
    attribute GSR of FF_59 : label is "ENABLED";
    attribute GSR of FF_58 : label is "ENABLED";
    attribute GSR of FF_57 : label is "ENABLED";
    attribute GSR of FF_56 : label is "ENABLED";
    attribute GSR of FF_55 : label is "ENABLED";
    attribute GSR of FF_54 : label is "ENABLED";
    attribute GSR of FF_53 : label is "ENABLED";
    attribute GSR of FF_52 : label is "ENABLED";
    attribute GSR of FF_51 : label is "ENABLED";
    attribute GSR of FF_50 : label is "ENABLED";
    attribute GSR of FF_49 : label is "ENABLED";
    attribute GSR of FF_48 : label is "ENABLED";
    attribute GSR of FF_47 : label is "ENABLED";
    attribute GSR of FF_46 : label is "ENABLED";
    attribute GSR of FF_45 : label is "ENABLED";
    attribute GSR of FF_44 : label is "ENABLED";
    attribute GSR of FF_43 : label is "ENABLED";
    attribute GSR of FF_42 : label is "ENABLED";
    attribute GSR of FF_41 : label is "ENABLED";
    attribute GSR of FF_40 : label is "ENABLED";
    attribute GSR of FF_39 : label is "ENABLED";
    attribute GSR of FF_38 : label is "ENABLED";
    attribute GSR of FF_37 : label is "ENABLED";
    attribute GSR of FF_36 : label is "ENABLED";
    attribute GSR of FF_35 : label is "ENABLED";
    attribute GSR of FF_34 : label is "ENABLED";
    attribute GSR of FF_33 : label is "ENABLED";
    attribute GSR of FF_32 : label is "ENABLED";
    attribute GSR of FF_31 : label is "ENABLED";
    attribute GSR of FF_30 : label is "ENABLED";
    attribute GSR of FF_29 : label is "ENABLED";
    attribute GSR of FF_28 : label is "ENABLED";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute MEM_INIT_FILE of fifo_pfu_0_0 : label is "(0-7)(0-3)";
    attribute MEM_LPC_FILE of fifo_pfu_0_0 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_0 : label is "fifo_pfu_0_0";
    attribute MEM_INIT_FILE of fifo_pfu_0_1 : label is "(0-7)(4-7)";
    attribute MEM_LPC_FILE of fifo_pfu_0_1 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_1 : label is "fifo_pfu_0_1";
    attribute MEM_INIT_FILE of fifo_pfu_0_2 : label is "(0-7)(8-11)";
    attribute MEM_LPC_FILE of fifo_pfu_0_2 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_2 : label is "fifo_pfu_0_2";
    attribute MEM_INIT_FILE of fifo_pfu_0_3 : label is "(0-7)(12-15)";
    attribute MEM_LPC_FILE of fifo_pfu_0_3 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_3 : label is "fifo_pfu_0_3";
    attribute MEM_INIT_FILE of fifo_pfu_0_4 : label is "(0-7)(16-19)";
    attribute MEM_LPC_FILE of fifo_pfu_0_4 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_4 : label is "fifo_pfu_0_4";
    attribute MEM_INIT_FILE of fifo_pfu_0_5 : label is "(0-7)(20-23)";
    attribute MEM_LPC_FILE of fifo_pfu_0_5 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_5 : label is "fifo_pfu_0_5";
    attribute MEM_INIT_FILE of fifo_pfu_0_6 : label is "(0-7)(24-27)";
    attribute MEM_LPC_FILE of fifo_pfu_0_6 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_6 : label is "fifo_pfu_0_6";
    attribute MEM_INIT_FILE of fifo_pfu_0_7 : label is "(0-7)(28-31)";
    attribute MEM_LPC_FILE of fifo_pfu_0_7 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_7 : label is "fifo_pfu_0_7";
    attribute MEM_INIT_FILE of fifo_pfu_0_8 : label is "(0-7)(32-35)";
    attribute MEM_LPC_FILE of fifo_pfu_0_8 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_8 : label is "fifo_pfu_0_8";
    attribute MEM_INIT_FILE of fifo_pfu_0_9 : label is "(0-7)(36-39)";
    attribute MEM_LPC_FILE of fifo_pfu_0_9 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_9 : label is "fifo_pfu_0_9";
    attribute MEM_INIT_FILE of fifo_pfu_0_10 : label is "(0-7)(40-43)";
    attribute MEM_LPC_FILE of fifo_pfu_0_10 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_10 : label is "fifo_pfu_0_10";
    attribute MEM_INIT_FILE of fifo_pfu_0_11 : label is "(0-7)(44-47)";
    attribute MEM_LPC_FILE of fifo_pfu_0_11 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_11 : label is "fifo_pfu_0_11";
    attribute MEM_INIT_FILE of fifo_pfu_0_12 : label is "(0-7)(48-48)";
    attribute MEM_LPC_FILE of fifo_pfu_0_12 : label is "pci_read_request_fifo.lpc";
    attribute COMP of fifo_pfu_0_12 : label is "fifo_pfu_0_12";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    AND2_t3: AND2
        port map (A=>WrEn, B=>invout_1, Z=>wren_i);

    INV_3: INV
        port map (A=>full_i, Z=>invout_1);

    AND2_t2: AND2
        port map (A=>RdEn, B=>invout_0, Z=>rden_i);

    INV_2: INV
        port map (A=>empty_i, Z=>invout_0);

    AND2_t1: AND2
        port map (A=>wren_i, B=>rden_i_inv, Z=>cnt_con);

    XOR2_t0: XOR2
        port map (A=>wren_i, B=>rden_i, Z=>fcnt_en);

    INV_1: INV
        port map (A=>rden_i, Z=>rden_i_inv);

    INV_0: INV
        port map (A=>wren_i, Z=>wren_i_inv);

    LUT4_2: ROM16X1A
        generic map (initval=> X"3232")
        port map (AD3=>scuba_vlo, AD2=>cmp_le_1, AD1=>wren_i,
            AD0=>empty_i, DO0=>empty_d);

    LUT4_1: ROM16X1A
        generic map (initval=> X"3232")
        port map (AD3=>scuba_vlo, AD2=>cmp_ge_d1, AD1=>rden_i,
            AD0=>full_i, DO0=>full_d);

    LUT4_0: ROM16X1A
        generic map (initval=> X"8000")
        port map (AD3=>scuba_vhi, AD2=>wren_i, AD1=>scuba_vhi,
            AD0=>scuba_vhi, DO0=>dec0_wre3);

    FF_111: FD1P3DX
        port map (D=>ifcount_0, SP=>fcnt_en, CK=>Clock, CD=>Reset,
            Q=>fcount_0);

    FF_110: FD1P3DX
        port map (D=>ifcount_1, SP=>fcnt_en, CK=>Clock, CD=>Reset,
            Q=>fcount_1);

    FF_109: FD1P3DX
        port map (D=>ifcount_2, SP=>fcnt_en, CK=>Clock, CD=>Reset,
            Q=>fcount_2);

    FF_108: FD1P3DX
        port map (D=>ifcount_3, SP=>fcnt_en, CK=>Clock, CD=>Reset,
            Q=>fcount_3);

    FF_107: FD1S3BX
        port map (D=>empty_d, CK=>Clock, PD=>Reset, Q=>empty_i);

    FF_106: FD1S3DX
        port map (D=>full_d, CK=>Clock, CD=>Reset, Q=>full_i);

    FF_105: FD1P3DX
        port map (D=>iwcount_0, SP=>wren_i, CK=>Clock, CD=>Reset,
            Q=>wcount_0);

    FF_104: FD1P3DX
        port map (D=>iwcount_1, SP=>wren_i, CK=>Clock, CD=>Reset,
            Q=>wcount_1);

    FF_103: FD1P3DX
        port map (D=>iwcount_2, SP=>wren_i, CK=>Clock, CD=>Reset,
            Q=>wcount_2);

    FF_102: FD1P3DX
        port map (D=>iwcount_3, SP=>wren_i, CK=>Clock, CD=>Reset,
            Q=>wcount_3);

    FF_101: FD1P3DX
        port map (D=>ircount_0, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>rcount_0);

    FF_100: FD1P3DX
        port map (D=>ircount_1, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>rcount_1);

    FF_99: FD1P3DX
        port map (D=>ircount_2, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>rcount_2);

    FF_98: FD1P3DX
        port map (D=>ircount_3, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>rcount_3);

    FF_97: FD1P3DX
        port map (D=>edataout0, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(0));

    FF_96: FD1P3DX
        port map (D=>rdataout0, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout0);

    FF_95: FD1P3DX
        port map (D=>edataout1, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(1));

    FF_94: FD1P3DX
        port map (D=>rdataout1, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout1);

    FF_93: FD1P3DX
        port map (D=>edataout2, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(2));

    FF_92: FD1P3DX
        port map (D=>rdataout2, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout2);

    FF_91: FD1P3DX
        port map (D=>edataout3, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(3));

    FF_90: FD1P3DX
        port map (D=>rdataout3, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout3);

    FF_89: FD1P3DX
        port map (D=>edataout4, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(4));

    FF_88: FD1P3DX
        port map (D=>rdataout4, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout4);

    FF_87: FD1P3DX
        port map (D=>edataout5, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(5));

    FF_86: FD1P3DX
        port map (D=>rdataout5, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout5);

    FF_85: FD1P3DX
        port map (D=>edataout6, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(6));

    FF_84: FD1P3DX
        port map (D=>rdataout6, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout6);

    FF_83: FD1P3DX
        port map (D=>edataout7, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(7));

    FF_82: FD1P3DX
        port map (D=>rdataout7, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout7);

    FF_81: FD1P3DX
        port map (D=>edataout8, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(8));

    FF_80: FD1P3DX
        port map (D=>rdataout8, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout8);

    FF_79: FD1P3DX
        port map (D=>edataout9, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(9));

    FF_78: FD1P3DX
        port map (D=>rdataout9, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout9);

    FF_77: FD1P3DX
        port map (D=>edataout10, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(10));

    FF_76: FD1P3DX
        port map (D=>rdataout10, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout10);

    FF_75: FD1P3DX
        port map (D=>edataout11, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(11));

    FF_74: FD1P3DX
        port map (D=>rdataout11, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout11);

    FF_73: FD1P3DX
        port map (D=>edataout12, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(12));

    FF_72: FD1P3DX
        port map (D=>rdataout12, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout12);

    FF_71: FD1P3DX
        port map (D=>edataout13, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(13));

    FF_70: FD1P3DX
        port map (D=>rdataout13, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout13);

    FF_69: FD1P3DX
        port map (D=>edataout14, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(14));

    FF_68: FD1P3DX
        port map (D=>rdataout14, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout14);

    FF_67: FD1P3DX
        port map (D=>edataout15, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(15));

    FF_66: FD1P3DX
        port map (D=>rdataout15, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout15);

    FF_65: FD1P3DX
        port map (D=>edataout16, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(16));

    FF_64: FD1P3DX
        port map (D=>rdataout16, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout16);

    FF_63: FD1P3DX
        port map (D=>edataout17, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(17));

    FF_62: FD1P3DX
        port map (D=>rdataout17, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout17);

    FF_61: FD1P3DX
        port map (D=>edataout18, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(18));

    FF_60: FD1P3DX
        port map (D=>rdataout18, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout18);

    FF_59: FD1P3DX
        port map (D=>edataout19, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(19));

    FF_58: FD1P3DX
        port map (D=>rdataout19, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout19);

    FF_57: FD1P3DX
        port map (D=>edataout20, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(20));

    FF_56: FD1P3DX
        port map (D=>rdataout20, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout20);

    FF_55: FD1P3DX
        port map (D=>edataout21, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(21));

    FF_54: FD1P3DX
        port map (D=>rdataout21, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout21);

    FF_53: FD1P3DX
        port map (D=>edataout22, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(22));

    FF_52: FD1P3DX
        port map (D=>rdataout22, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout22);

    FF_51: FD1P3DX
        port map (D=>edataout23, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(23));

    FF_50: FD1P3DX
        port map (D=>rdataout23, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout23);

    FF_49: FD1P3DX
        port map (D=>edataout24, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(24));

    FF_48: FD1P3DX
        port map (D=>rdataout24, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout24);

    FF_47: FD1P3DX
        port map (D=>edataout25, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(25));

    FF_46: FD1P3DX
        port map (D=>rdataout25, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout25);

    FF_45: FD1P3DX
        port map (D=>edataout26, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(26));

    FF_44: FD1P3DX
        port map (D=>rdataout26, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout26);

    FF_43: FD1P3DX
        port map (D=>edataout27, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(27));

    FF_42: FD1P3DX
        port map (D=>rdataout27, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout27);

    FF_41: FD1P3DX
        port map (D=>edataout28, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(28));

    FF_40: FD1P3DX
        port map (D=>rdataout28, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout28);

    FF_39: FD1P3DX
        port map (D=>edataout29, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(29));

    FF_38: FD1P3DX
        port map (D=>rdataout29, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout29);

    FF_37: FD1P3DX
        port map (D=>edataout30, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(30));

    FF_36: FD1P3DX
        port map (D=>rdataout30, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout30);

    FF_35: FD1P3DX
        port map (D=>edataout31, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(31));

    FF_34: FD1P3DX
        port map (D=>rdataout31, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout31);

    FF_33: FD1P3DX
        port map (D=>edataout32, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(32));

    FF_32: FD1P3DX
        port map (D=>rdataout32, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout32);

    FF_31: FD1P3DX
        port map (D=>edataout33, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(33));

    FF_30: FD1P3DX
        port map (D=>rdataout33, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout33);

    FF_29: FD1P3DX
        port map (D=>edataout34, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(34));

    FF_28: FD1P3DX
        port map (D=>rdataout34, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout34);

    FF_27: FD1P3DX
        port map (D=>edataout35, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(35));

    FF_26: FD1P3DX
        port map (D=>rdataout35, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout35);

    FF_25: FD1P3DX
        port map (D=>edataout36, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(36));

    FF_24: FD1P3DX
        port map (D=>rdataout36, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout36);

    FF_23: FD1P3DX
        port map (D=>edataout37, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(37));

    FF_22: FD1P3DX
        port map (D=>rdataout37, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout37);

    FF_21: FD1P3DX
        port map (D=>edataout38, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(38));

    FF_20: FD1P3DX
        port map (D=>rdataout38, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout38);

    FF_19: FD1P3DX
        port map (D=>edataout39, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(39));

    FF_18: FD1P3DX
        port map (D=>rdataout39, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout39);

    FF_17: FD1P3DX
        port map (D=>edataout40, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(40));

    FF_16: FD1P3DX
        port map (D=>rdataout40, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout40);

    FF_15: FD1P3DX
        port map (D=>edataout41, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(41));

    FF_14: FD1P3DX
        port map (D=>rdataout41, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout41);

    FF_13: FD1P3DX
        port map (D=>edataout42, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(42));

    FF_12: FD1P3DX
        port map (D=>rdataout42, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout42);

    FF_11: FD1P3DX
        port map (D=>edataout43, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(43));

    FF_10: FD1P3DX
        port map (D=>rdataout43, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout43);

    FF_9: FD1P3DX
        port map (D=>edataout44, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(44));

    FF_8: FD1P3DX
        port map (D=>rdataout44, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout44);

    FF_7: FD1P3DX
        port map (D=>edataout45, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(45));

    FF_6: FD1P3DX
        port map (D=>rdataout45, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout45);

    FF_5: FD1P3DX
        port map (D=>edataout46, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(46));

    FF_4: FD1P3DX
        port map (D=>rdataout46, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout46);

    FF_3: FD1P3DX
        port map (D=>edataout47, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(47));

    FF_2: FD1P3DX
        port map (D=>rdataout47, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout47);

    FF_1: FD1P3DX
        port map (D=>edataout48, SP=>scuba_vhi, CK=>Clock, CD=>Reset,
            Q=>Q(48));

    FF_0: FD1P3DX
        port map (D=>rdataout48, SP=>rden_i, CK=>Clock, CD=>Reset,
            Q=>edataout48);

    bdcnt_bctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>cnt_con, B0=>scuba_vlo, B1=>cnt_con,
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi,
            CIN=>'X', S0=>open, S1=>open, COUT=>bdcnt_bctr_ci);

    bdcnt_bctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA",
        INIT0=> X"99AA")
        port map (A0=>fcount_0, A1=>fcount_1, B0=>cnt_con, B1=>cnt_con,
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi,
            CIN=>bdcnt_bctr_ci, S0=>ifcount_0, S1=>ifcount_1, COUT=>co0);

    bdcnt_bctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA",
        INIT0=> X"99AA")
        port map (A0=>fcount_2, A1=>fcount_3, B0=>cnt_con, B1=>cnt_con,
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi,
            CIN=>co0, S0=>ifcount_2, S1=>ifcount_3, COUT=>co1);

    e_cmp_ci_a: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>scuba_vhi, A1=>scuba_vhi, B0=>scuba_vhi,
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>cmp_ci);

    e_cmp_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA",
        INIT0=> X"99AA")
        port map (A0=>rden_i, A1=>scuba_vlo, B0=>fcount_0, B1=>fcount_1,
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi,
            CIN=>cmp_ci, S0=>open, S1=>open, COUT=>co0_1);

    e_cmp_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA",
        INIT0=> X"99AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>fcount_2,
            B1=>fcount_3, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>co0_1, S0=>open, S1=>open,
            COUT=>cmp_le_1_c);

    a0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo,
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>cmp_le_1_c, S0=>cmp_le_1, S1=>open,
            COUT=>open);

    g_cmp_ci_a: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>scuba_vhi, A1=>scuba_vhi, B0=>scuba_vhi,
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>cmp_ci_1);

    g_cmp_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA",
        INIT0=> X"99AA")
        port map (A0=>fcount_0, A1=>fcount_1, B0=>wren_i, B1=>wren_i,
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi,
            CIN=>cmp_ci_1, S0=>open, S1=>open, COUT=>co0_2);

    g_cmp_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA",
        INIT0=> X"99AA")
        port map (A0=>fcount_2, A1=>fcount_3, B0=>wren_i, B1=>wren_i_inv,
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi,
            CIN=>co0_2, S0=>open, S1=>open, COUT=>cmp_ge_d1_c);

    a1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo,
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>cmp_ge_d1_c, S0=>cmp_ge_d1, S1=>open,
            COUT=>open);

    w_ctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo,
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>w_ctr_ci);

    w_ctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>wcount_0, A1=>wcount_1, B0=>scuba_vlo,
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>w_ctr_ci, S0=>iwcount_0, S1=>iwcount_1,
            COUT=>co0_3);

    w_ctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>wcount_2, A1=>wcount_3, B0=>scuba_vlo,
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>co0_3, S0=>iwcount_2, S1=>iwcount_3,
            COUT=>co1_1);

    r_ctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo,
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>r_ctr_ci);

    r_ctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>rcount_0, A1=>rcount_1, B0=>scuba_vlo,
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>r_ctr_ci, S0=>ircount_0, S1=>ircount_1,
            COUT=>co0_4);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    r_ctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA",
        INIT0=> X"66AA")
        port map (A0=>rcount_2, A1=>rcount_3, B0=>scuba_vlo,
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi,
            D1=>scuba_vhi, CIN=>co0_4, S0=>ircount_2, S1=>ircount_3,
            COUT=>co1_2);

    fifo_pfu_0_0: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(48), DI1=>scuba_vhi, DI2=>scuba_vhi,
            DI3=>scuba_vhi, WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout48, DO1=>open, DO2=>open,
            DO3=>open);

    fifo_pfu_0_1: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(44), DI1=>Data(45), DI2=>Data(46),
            DI3=>Data(47), WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout44, DO1=>rdataout45,
            DO2=>rdataout46, DO3=>rdataout47);

    fifo_pfu_0_2: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(40), DI1=>Data(41), DI2=>Data(42),
            DI3=>Data(43), WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout40, DO1=>rdataout41,
            DO2=>rdataout42, DO3=>rdataout43);

    fifo_pfu_0_3: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(36), DI1=>Data(37), DI2=>Data(38),
            DI3=>Data(39), WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout36, DO1=>rdataout37,
            DO2=>rdataout38, DO3=>rdataout39);

    fifo_pfu_0_4: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(32), DI1=>Data(33), DI2=>Data(34),
            DI3=>Data(35), WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout32, DO1=>rdataout33,
            DO2=>rdataout34, DO3=>rdataout35);

    fifo_pfu_0_5: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(28), DI1=>Data(29), DI2=>Data(30),
            DI3=>Data(31), WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout28, DO1=>rdataout29,
            DO2=>rdataout30, DO3=>rdataout31);

    fifo_pfu_0_6: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(24), DI1=>Data(25), DI2=>Data(26),
            DI3=>Data(27), WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout24, DO1=>rdataout25,
            DO2=>rdataout26, DO3=>rdataout27);

    fifo_pfu_0_7: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(20), DI1=>Data(21), DI2=>Data(22),
            DI3=>Data(23), WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout20, DO1=>rdataout21,
            DO2=>rdataout22, DO3=>rdataout23);

    fifo_pfu_0_8: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(16), DI1=>Data(17), DI2=>Data(18),
            DI3=>Data(19), WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout16, DO1=>rdataout17,
            DO2=>rdataout18, DO3=>rdataout19);

    fifo_pfu_0_9: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(12), DI1=>Data(13), DI2=>Data(14),
            DI3=>Data(15), WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout12, DO1=>rdataout13,
            DO2=>rdataout14, DO3=>rdataout15);

    fifo_pfu_0_10: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(8), DI1=>Data(9), DI2=>Data(10),
            DI3=>Data(11), WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0,
            RAD1=>rcount_1, RAD2=>rcount_2, RAD3=>scuba_vhi,
            WAD0=>wcount_0, WAD1=>wcount_1, WAD2=>wcount_2,
            WAD3=>scuba_vhi, DO0=>rdataout8, DO1=>rdataout9,
            DO2=>rdataout10, DO3=>rdataout11);

    fifo_pfu_0_11: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(4), DI1=>Data(5), DI2=>Data(6), DI3=>Data(7),
            WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0, RAD1=>rcount_1,
            RAD2=>rcount_2, RAD3=>scuba_vhi, WAD0=>wcount_0,
            WAD1=>wcount_1, WAD2=>wcount_2, WAD3=>scuba_vhi,
            DO0=>rdataout4, DO1=>rdataout5, DO2=>rdataout6,
            DO3=>rdataout7);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    fifo_pfu_0_12: DPR16X4C
        generic map (initval=> "0x0000000000000000")
        port map (DI0=>Data(0), DI1=>Data(1), DI2=>Data(2), DI3=>Data(3),
            WCK=>Clock, WRE=>dec0_wre3, RAD0=>rcount_0, RAD1=>rcount_1,
            RAD2=>rcount_2, RAD3=>scuba_vhi, WAD0=>wcount_0,
            WAD1=>wcount_1, WAD2=>wcount_2, WAD3=>scuba_vhi,
            DO0=>rdataout0, DO1=>rdataout1, DO2=>rdataout2,
            DO3=>rdataout3);

    Empty <= empty_i;
    Full <= full_i;
end Structure;
